<?php
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 05/10/2017
 * Time: 13:37
 */
require_once "Person.php";

class Mecdcin extends Person
{
    private $matricule;

    public function __construct()
    {
    }
    public function init($id, $firstname, $lastname, $phone, $mail, $username, $password,$matricule)
    {
        parent::init($id, $firstname, $lastname, $phone, $mail, $username, $password); // TODO: Change the autogenerated stub
        $this->matricule=$matricule;
    }


    /**
     * @return mixed
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * @param mixed $matricule
     */
    public function setMatricule($matricule)
    {
        $this->matricule = $matricule;
    }

    public function __toString()
    {
        return "Medecin : {"+parent::__toString()+"}"; // TODO: Change the autogenerated stub
    }


}